apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ctst0qtms-python 
  janus-idp.io/tekton: ctst0qtms-python
  backstage.io/kubernetes-id: ctst0qtms-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ctst0qtms-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml