apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ctst0qtms-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ctst0qtms-python 
  name: ctst0qtms-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ctst0qtms-python 
